
server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: "/"
spring:
#  profiles:
#    active: test
  servlet:
    multipart:
      max-file-size: 5MB
  thymeleaf:
    # 开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    # 模板编码
    encoding: utf-8
    # 开启模板缓存（默认值：true）,强烈建议，开发模式下不开启缓存
    cache: false
    # 在渲染之前检查模板是否存在
    check-template: true
    # 检查模板位置是否正确（默认值:true）
    check-template-location: true
    # Content-Type的值（默认值：text/html）
    servlet:
      content-type: text/html
    # 要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML
    # 在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）,后缀(默认值.html)
    prefix: classpath:/templates
    suffix: .html
  datasource:
    name: wxds
    url: jdbc:mysql://localhost:3306/wxapplets?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  # 设置json convert时的时区为中国
  jackson:
    time-zone: GMT+8
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
# 暴露 actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# =============分布式文件系统FDFS配置 https://github.com/tobato/FastDFS_Client================

fdfs:
  soTimeout: 60
  connectTimeout: 60
  thumbImage:  # 缩略图生成参数
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个
    - 192.168.0.244:22122
  pool:
    max-total: 100
    max-wait-millis: 60
  returnServerAndGroup: "192.168.0.244:9998/group1/"
